[package]
name = "effector-swc-plugin"
version = "0.1.0"

authors = ["Kireev Mikhail"]
description = "SWC Plugin for Effector"

edition = "2021"
publish = false

[profile.release]
lto = true

[dependencies]
ahash = { version = "0.8.7", features = ["std"], default-features = false }
radix_fmt = "1.0.0"
serde = "1"
serde_json = "1"
swc_core = { version = "~0.88", features = ["ecma_plugin_transform", "ecma_quote", "ecma_utils"] }

[dev-dependencies]
swc_ecma_parser = "~0.142"
testing = "0.35.14"

[features]
packing = []

[lib]
crate-type = ["cdylib", "rlib"]
