[package]
name = "effector-swc-plugin"
version = "0.2.2"

authors = ["Kireev Mikhail"]
description = "SWC Plugin for Effector"

edition = "2021"
publish = false

[profile.release]
lto = true
debug = "none"
strip = "debuginfo"

[dependencies]
ahash = { version = "0.8.8", features = ["std"], default-features = false }
radix_fmt = "1.0.0"
serde = "1"
serde_json = "1"
swc_core = { version = "~0.90.6", features = [
  "ecma_plugin_transform",
  "ecma_quote",
  "ecma_utils",
  "ecma_parser",
] }

[dev-dependencies]
testing = "0.35.14"

[features]
packing = []
plugin_compat_v1 = []

[lib]
crate-type = ["cdylib", "rlib"]
