version = "Two"
unstable_features = true
style_edition = "2024"

format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
normalize_doc_attributes = true

imports_granularity = "Crate"

newline_style = "Unix"

error_on_line_overflow = true

use_field_init_shorthand = true
use_try_shorthand = true

format_macro_bodies = true
format_macro_matchers = true

group_imports = "StdExternalCrate"

max_width = 90
struct_field_align_threshold = 4
single_line_let_else_max_width = 80
struct_lit_width = 60
