version = "Two"
unstable_features = true

format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
normalize_doc_attributes = true

imports_granularity = "Crate"

newline_style = "unix"

error_on_line_overflow = true

use_field_init_shorthand = true
use_try_shorthand = true

format_macro_bodies = true
format_macro_matchers = true

group_imports = "StdExternalCrate"
